name: openaccountsgetx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5-210.2.beta <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  email_validator: '^2.1.16'
  datepicker_dropdown: ^0.0.7
  flutter: 
    sdk: flutter
  time_machine: ^0.9.17
  simple_circular_progress_bar: ^1.0.2
  auto_size_text: ^3.0.0
  http: ^1.1.0
  thai_idcard_reader_flutter: ^0.0.7

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

